version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/package" # Location of package manifests
    schedule:
      interval: "daily"
