name: "build-test-release"
on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [main, develop]

permissions:
  contents: write
  packages: read
  pull-requests: read
  statuses: write

jobs:
  local-appinspect:
    runs-on: ubuntu-latest
    steps:
      - uses: splunk/appinspect-cli-action@v2.0.2
        with:
          included_tags: "private_victoria"
          app_path: "output/app"

        #   - name: Upload package
        #   uses: actions/upload-artifact@v3
        #   with:
        #     name: x-1.0.0.tar.gz
        #     path: ./x-1.0.0.tar.gz
